# Generated by Django 3.0.3 on 2022-03-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('O', 'Old Books'), ('N', 'New Books')], default='Classic', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Classic'), ('N', 'Novel'), ('F', 'Fiction'), ('A', 'Adventure'), ('H', 'Horror'), ('E', 'Educational'), ('K', 'Kids'), ('M', 'Mystery'), ('T', 'Thriller'), ('R', 'Realistic'), ('S', 'Sports'), ('I', 'Inspirational')], max_length=12),
        ),
    ]
